version: "3.8"
services:
    app:
        restart: always
        image: automl-rdatasets
        build:
            dockerfile: ./Dockerfile
            context: .
        volumes:
          - .:/home/app/webapp
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}